//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public int CourseId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short Price { get; set; }
        public string LevelString { get; set; }
        public byte Level { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
    }
}
